[project]
name = "mars-to-zarr"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Kasper Hintz", email = "kah@dmi.dk"},
]
dependencies = [
    "ecmwf-api-client>=1.6.5",
    "xarray>=2025",
    "zarr<3",
    "loguru>=0.7.3",
    "pyyaml>=6.0.2",
    "fsspec>=2025.3.2",
    "gribscan>=0.0.14",
    "isodate>=0.7.2",
    "scipy>=1.15.2",
    "dask>=2025.4.1",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=4.2.0",
]
